### PR TITLE
Add maybeKey combinator

### LINKED ISSUE #36: A combinator for missing values
The following version of the `key` allows for running `parseEither` against object mappings with missing optional fields (imagine a "Remember me" checkbox field that may be absent from a payload if not selected by a user). It would be nice to see it distributed within the package:

```haskell
maybeKey :: ACD.Key -> ACD.Decoder a -> ACD.Decoder (Maybe a)
maybeKey t (ACD.Decoder d) = ACD.Decoder $ \case
  AT.Object v -> p >>= maybe (pure Nothing) (fmap Just . d)
    where
        p = v .:? t
  val      -> AT.typeMismatch "Object" val
{-# INLINE maybeKey #-}
```

It's pretty much the same `key` but `.:?` is used instead of `.:` for the inner parser.

### PR DESCRIPTION
**Pull request by avanov**
Resolves #36

### CODE REVIEW

**Review by turboMaCk — APPROVED** [review]
LGTM

**Comment by avanov** [comment]
Oh, I forgot to remove the qualified prefix after copying the snippet from my local module. I’ll fix it…

**Comment by turboMaCk** [comment]
released in 0.1.1.0

**Comment by avanov** [comment]
Thank you!

**Pull request merged**
